url: "https://robot-dreams-de-api.herokuapp.com"
endpoint_data: "/out_of_stock"
endpoint_auth: "/auth"
payload: {"date": "2021-12-01"}
credentials: {"username": "rd_dreams", "password": "djT6LasE"}
root_folder: "./data/"


